# -*- coding: utf-8 -*-
"""tomato_leaf_disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k0Tinddwn2DRMfNDjzYof2dGBan8MpFI
"""

#!pip install tensorflow

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing import image
import os

from google.colab import files
uploaded = files.upload()  # Upload the ZIP file manually

import zipfile

# Path to your uploaded zip file
zip_file_path = "/content/archive (1).zip"
extract_path = "/content/dataset"  # You can change the destination path if needed

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os

data_dir = "/content/dataset/tomato/train"  # Adjust if your structure is different

print("📂 Categories:")
for folder in os.listdir(data_dir):
    print("-", folder)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_data = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_directory(
    data_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    MaxPooling2D(2, 2),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(train_data.num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

model.save("tomato_disease_model.h5")

import numpy as np
from tensorflow.keras.preprocessing import image

# Upload a test image
from google.colab import files
uploaded = files.upload()

# Load and predict
img_path = list(uploaded.keys())[0]
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)
predicted_class = np.argmax(prediction)
class_names = list(train_data.class_indices.keys())
print("Predicted Class:", class_names[predicted_class])

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Training vs Validation Accuracy")
plt.show()

!pip install flask-ngrok

import os
print(os.getcwd())  # Get the current working directory
print(os.listdir())  # List all files in the current directory

!pip install flask tensorflow

pip install flask-cors

from flask_cors import CORS

!pip install pyngrok

app = Flask(__name__)
CORS(app)  # Enable CORS

public_url = ngrok.connect(5000)
print(" * ngrok tunnel running at:", public_url)

from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok
from PIL import Image
import numpy as np
import tensorflow as tf

app = Flask(__name__)
CORS(app)  # This allows cross-origin requests

# Load model, etc...

from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok
from PIL import Image
import numpy as np
import tensorflow as tf
import os

app = Flask(__name__)
CORS(app)  # Enable CORS for all routes

# Load the model only once
model_path = 'tomato_disease_model.h5'
if not os.path.exists(model_path):
    raise FileNotFoundError(f"Model file not found: {model_path}")
model = tf.keras.models.load_model(model_path)

# Class labels (Make sure the order matches the model output)
class_labels = [
    'Tomato___Bacterial_spot',
    'Tomato___Early_blight',
    'Tomato___Late_blight',
    'Tomato___Leaf_Mold',
    'Tomato___Septoria_leaf_spot',
    'Tomato___Spider_mites Two-spotted_spider_mite',
    'Tomato___Target_Spot',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
    'Tomato___Tomato_mosaic_virus',
    'Tomato___healthy'
]

# Helper: Preprocess the image for prediction
def prepare_image(image):
    image = image.resize((224, 224))  # Make sure this matches your model's input
    image = np.array(image) / 255.0
    if image.shape[-1] == 4:
        image = image[..., :3]  # Convert RGBA to RGB
    image = np.expand_dims(image, axis=0)
    return image

@app.route('/predict', methods=['POST'])
def predict():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'})

    file = request.files['file']

    if file.filename == '':
        return jsonify({'error': 'No selected file'})

    try:
        image = Image.open(file.stream).convert('RGB')
        processed_image = prepare_image(image)
        prediction = model.predict(processed_image)
        predicted_label = class_labels[np.argmax(prediction)]
        return jsonify({'prediction': predicted_label})

    except Exception as e:
        return jsonify({'error': f'Prediction failed: {str(e)}'})

if __name__ == '__main__':
    # Start ngrok tunnel
    port = 5000
    public_url = ngrok.connect(port)
    print(" * ngrok tunnel running at:", public_url)

    # Start Flask app
    app.run(host='0.0.0.0', port=port, debug=False, threaded=True)
